### ISSUE TITLE
Can't install mod

### ISSUE THREAD

**Issue by ggyyhh220** [johmarjac/MordhauModManager#2]
When I tried to install a mod,it says mod installation failed,please cotact developer.
![CIQ3$A{I2C5`}RBTHHZOBMU](https://user-images.githubusercontent.com/64685078/80860860-23681800-8c9d-11ea-93b2-08cfb5c86e73.png)

**Comment by johmarjac** [comment]
Have you ever played a server with mods? Can you please locate the .modio folder in your mordhau installation directory and make a zip file out of it and attach it to here?

**Comment by ggyyhh220** [comment]
I think I haven't.Here's the zip file.(I can't upload files bigger than 10mb)



[.modio01.zip](https://github.com/johmarjac/MordhauModManager/files/4573115/default.modio01.zip)
[.modio02.zip](https://github.com/johmarjac/MordhauModManager/files/4573116/default.modio02.zip)
[.modio03.zip](https://github.com/johmarjac/MordhauModManager/files/4573117/default.modio03.zip)
[.modio04.zip](https://github.com/johmarjac/MordhauModManager/files/4573118/default.modio04.zip)
[.modio05.zip](https://github.com/johmarjac/MordhauModManager/files/4573119/default.modio05.zip)
[.modio06.zip](https://github.com/johmarjac/MordhauModManager/files/4573120/default.modio06.zip)
[.modio07.zip](https://github.com/johmarjac/MordhauModManager/files/4573121/default.modio07.zip)
[.modio08.zip](https://github.com/johmarjac/MordhauModManager/files/4573122/default.modio08.zip)
[.modio09.zip](https://github.com/johmarjac/MordhauModManager/files/4573123/default.modio09.zip)
[.modio10.zip](https://github.com/johmarjac/MordhauModManager/files/4573124/default.modio10.zip)
[.modio11.zip](https://github.com/johmarjac/MordhauModManager/files/4573125/default.modio11.zip)
[.modio12.zip](https://github.com/johmarjac/MordhauModManager/files/4573126/default.modio12.zip)
[.modio13.zip](https://github.com/johmarjac/MordhauModManager/files/4573127/default.modio13.zip)
[.modio14.zip](https://github.com/johmarjac/MordhauModManager/files/4573128/default.modio14.zip)
[.modio15.zip](https://github.com/johmarjac/MordhauModManager/files/4573129/default.modio15.zip)
[.modio16.zip](https://github.com/johmarjac/MordhauModManager/files/4573130/default.modio16.zip)
[.modio17.zip](https://github.com/johmarjac/MordhauModManager/files/4573131/default.modio17.zip)
[.modio18.zip](https://github.com/johmarjac/MordhauModManager/files/4573132/default.modio18.zip)
[.modio20.zip](https://github.com/johmarjac/MordhauModManager/files/4573133/default.modio20.zip)

**Comment by johmarjac** [comment]
Can you try to go ingame, join any modded server first then leave, close game and start the mod manager again and try again using it?

**Comment by ggyyhh220** [comment]
It's an amazing thing. When I entered the game, I found that these mod already existed in the "installed mod". It looks like the mod manager has no problem.
